In [7]:
! pip install numpy 
! pip install pandas

In [5]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv("C:/Users/sairu/Downloads/Indian_Cricket_Team_Dataset.csv")

In [8]:
df.head()

Player Name  Age  Matches Played  Batting Average  Strike Rate
0    Player_1   26             456            27.70       188.21
1    Player_2   23             154            24.61       139.34
2    Player_3   32             210            36.87       182.79
3    Player_4   34             426            51.81       178.77
4    Player_5   30             221            49.80       162.44

In [9]:
df1 = df.copy()

# Query 1: Convert 'Age' column to a NumPy array

In [11]:
age_array = df1['Age'].to_numpy
print(age_array)

<bound method IndexOpsMixin.to_numpy of 0      26
1      23
2      32
3      34
4      30
       ..
995    24
996    28
997    23
998    35
999    30
Name: Age, Length: 1000, dtype: int64>


# Query 2: Find the average age of player

In [16]:
mean_value = df1["Age"].mean()
print(mean_value)

27.57


# Query 3: Find the oldest and youngest player age. 

In [19]:
max_age = df1["Age"].max()
min_age = df1["Age"].min()
print(max_age)
print(min_age)


35
20


# Query 4: Count the total number of players above 30 years old.

In [20]:
count_age = df1["Age"] > 30
count = count_age.sum()
print(count)

336


# Query 5: Find the median batting average.

In [21]:
batting_average = df1["Batting Average"].median()
print(batting_average)

40.135


# Query 6: Find the standard deviation of strike rates.

In [22]:
standard_deviation = df1["Strike Rate"].std() 
print(standard_deviation)

29.122759125573694


# Query 7: Find the 90th percentile of batting average. 

In [24]:
batting_avg_90th_percentile = df1["Batting Average"].quantile(0.90)

print(batting_avg_90th_percentile)

55.323


# Query 8: Find the number of players with strike rate above 150. 

strike_rate = (df1["Strike Rate"] > 150).sum() 
print(strike_rate)

# Query 9: Reshape the first 20 batting averages into a 4x5 matrix. 

In [29]:
batting_avg_20 = df["Batting Average"].head(20).to_numpy()
batting_avg_matrix = batting_avg_20.reshape(4, 5)
print( batting_avg_matrix)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


# Query 10: Compute row-wise sum of reshaped matrix. 

In [30]:
batting_avg_20 = df["Batting Average"].head(20).to_numpy()
batting_avg_matrix = batting_avg_20.reshape(4, 5)
row_sums = batting_avg_matrix.sum(axis=1)
print(row_sums)

[190.79 193.1  212.87 210.42]


# Query 11: Compute column-wise mean of reshaped matrix. 

In [31]:
batting_avg_20 = df["Batting Average"].head(20).to_numpy()
batting_avg_matrix = batting_avg_20.reshape(4, 5)
col_means = batting_avg_matrix.mean(axis=0)
print(col_means)

[30.5325 35.3575 39.9775 51.2875 44.64  ]


# Query 12: Transpose the reshaped matrix. 

In [32]:
transpose = col_means.T
print(transpose)

[30.5325 35.3575 39.9775 51.2875 44.64  ]


# Query 13: Find the variance of batting average. 

In [33]:
variance = df["Batting Average"].var() 
print(variance)

131.6715008167167


# Query 14: Stack age and matches played horizontally.

In [34]:

age_array = df["Age"].to_numpy()
matches_played_array = df["Matches Played"].to_numpy()
stacked_array = np.column_stack((age_array, matches_played_array))
print( stacked_array)


[[ 26 456]
 [ 23 154]
 [ 32 210]
 ...
 [ 23 126]
 [ 35  16]
 [ 30 146]]


# Query 15: Split the batting average array into 5 equal parts.

In [36]:

batting_avg_array = df["Batting Average"].to_numpy()
batting_avg_splits = np.array_split(batting_avg_array, 5)
for i, part in enumerate(batting_avg_splits):
    print(f"Part {i+1}:\n", part)


Part 1:
 [27.7  24.61 36.87 51.81 49.8  22.2  38.21 40.9  45.78 46.01 34.59 42.43
 39.24 55.4  41.21 37.64 36.18 42.9  52.16 41.54 46.47 49.51 40.81 37.07
 55.07 36.7  38.48 59.61 20.01 27.42 35.36 57.3  22.8  20.38 22.11 23.54
 21.5  39.19 43.23 30.87 35.93 23.67 33.45 40.9  49.29 20.13 38.69 31.88
 54.11 48.62 43.56 31.09 56.41 21.8  24.38 35.67 24.98 58.26 51.92 30.36
 43.54 59.29 55.37 44.03 56.15 59.57 49.73 22.6  36.06 53.51 29.22 53.23
 24.81 21.88 35.36 21.47 58.29 53.05 52.03 45.19 28.65 40.73 43.89 41.
 30.41 40.61 39.65 59.85 55.9  38.54 44.92 49.91 21.39 55.8  54.41 38.3
 35.65 30.92 39.07 21.78 54.09 21.42 33.16 57.26 49.41 31.26 30.11 20.2
 47.83 21.95 41.3  58.48 24.38 55.78 59.66 22.46 55.32 40.64 56.26 42.85
 46.48 41.75 54.58 49.36 40.85 54.73 29.81 26.29 26.42 33.36 29.55 57.2
 24.23 47.96 27.57 55.27 58.45 38.62 55.16 20.21 52.8  29.15 56.35 20.04
 42.25 50.27 30.35 27.73 23.36 33.06 42.39 24.63 35.07 20.36 52.75 25.14
 31.33 20.74 37.29 53.6  35.69 27.18 50.15 51.5